name: StreamSplat
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.2=py39h06a4308_0
  - python=3.9.12=h12debd9_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
    - accelerate==1.0.1
    - aiofiles==23.2.1
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.10
    - aiosignal==1.3.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.6.2.post1
    - async-timeout==4.0.3
    - asyncer==0.0.8
    - attrs==24.2.0
    - certifi==2024.8.30
    - charset-normalizer==3.4.0
    - click==8.1.7
    - coloredlogs==15.0.1
    - contourpy==1.3.0
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - dearpygui==2.0.0
    - decord==0.6.0
    - deprecated==1.2.14
    - docstring-parser==0.16
    - einops==0.8.0
    - eval-type-backport==0.2.0
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastapi==0.115.2
    - ffmpy==0.4.0
    - filelock==3.13.1
    - filetype==1.2.0
    - flatbuffers==24.3.25
    - fonttools==4.54.1
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gradio==4.44.1
    - gradio-client==1.3.0
    - h11==0.14.0
    - httpcore==1.0.6
    - httpx==0.27.2
    - huggingface-hub==0.25.2
    - humanfriendly==10.0
    - idna==3.10
    - imageio==2.36.0
    - imageio-ffmpeg==0.5.1
    - importlib-resources==6.4.5
    - jinja2==3.1.3
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - kiui==0.2.14
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lightning-utilities==0.11.8
    - llvmlite==0.43.0
    - lpips==0.1.4
    - markdown-it-py==3.0.0
    - markupsafe==2.1.5
    - marshmallow==3.23.0
    - matplotlib==3.9.2
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.1.0
    - mypy-extensions==1.0.0
    - networkx==3.2.1
    - numba==0.60.0
    - numpy==1.26.3
    - nvidia-cublas-cu12==12.4.2.65
    - nvidia-cuda-cupti-cu12==12.4.99
    - nvidia-cuda-nvrtc-cu12==12.4.99
    - nvidia-cuda-runtime-cu12==12.4.99
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.0.44
    - nvidia-curand-cu12==10.3.5.119
    - nvidia-cusolver-cu12==11.6.0.99
    - nvidia-cusparse-cu12==12.3.0.142
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu12==12.4.99
    - objprint==0.2.3
    - omegaconf==2.3.0
    - onnxruntime==1.19.2
    - onnxruntime-gpu==1.19.2
    - opencv-python-headless==4.10.0.84
    - orjson==3.10.7
    - packaging==24.1
    - pandas==2.2.3
    - pillow==10.2.0
    - platformdirs==4.3.6
    - plyfile==1.1
    - pooch==1.8.2
    - propcache==0.2.0
    - protobuf==5.28.2
    - psutil==6.1.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydub==0.25.1
    - pygltflib==1.16.2
    - pygments==2.18.0
    - pymatting==1.1.12
    - pyparsing==3.2.0
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.12
    - pytz==2024.2
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.9.11
    - rembg==2.0.59
    - requests==2.32.3
    - rich==13.9.2
    - roma==1.5.0
    - rpds-py==0.20.0
    - ruff==0.7.0
    - safetensors==0.4.5
    - scikit-image==0.24.0
    - scikit-learn==1.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - shellingham==1.5.4
    - shtab==1.7.1
    - six==1.16.0
    - sniffio==1.3.1
    - starlette==0.40.0
    - sympy==1.13.1
    - threadpoolctl==3.5.0
    - tifffile==2024.8.30
    - tokenizers==0.20.1
    - tomlkit==0.12.0
    - torch==2.4.1+cu124
    - torchaudio==2.4.1+cu124
    - torchmetrics==1.4.3
    - torchvision==0.19.1+cu124
    - tqdm==4.66.5
    - transformers==4.45.2
    - trimesh==4.5.0
    - triton==3.0.0
    - typer==0.12.5
    - typing-extensions==4.9.0
    - typing-inspect==0.9.0
    - tyro==0.8.12
    - tzdata==2024.2
    - urllib3==2.2.3
    - uvicorn==0.32.0
    - varname==0.13.5
    - watchdog==5.0.3
    - websockets==12.0
    - wrapt==1.16.0
    - xatlas==0.0.9
    - xformers==0.0.28.post1
    - yarl==1.15.4
    - zipp==3.20.2
